# Generated by Django 5.0.6 on 2024-07-18 02:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, choices=[('Iphone', 'Iphone'), ('Laptop', 'Laptop'), ('Samsung', 'Samsung'), ('Iwatch', 'Iwatch')], max_length=300, null=True)),
                ('imei', models.IntegerField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('spec', models.CharField(max_length=300)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('checked_in_date', models.DateField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=300, null=True)),
                ('buyer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
