# Generated by Django 4.1.5 on 2023-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_phone_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('iphone 6', 'iphone 6'), ('iphone 14 pro', 'iphone 14 pro'), ('iphone 12', 'iphone 12'), ('techno', 'techno'), ('techno', 'techno')], max_length=300),
        ),
    ]
