# Generated by Django 4.1.5 on 2023-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_phone_date_sold_alter_phone_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='dent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, choices=[('samsung s10', 'samsung s10'), ('iphone 6', 'iphone 6')], max_length=300, null=True),
        ),
    ]
