# Generated by Django 4.1.5 on 2023-01-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_phone_dent_alter_phone_imei_alter_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='checked_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, choices=[('samsung s10', 'samsung s10'), ('iphone 6', 'iphone 6'), ('apple watch', 'apple watch')], max_length=300, null=True),
        ),
    ]
