# Generated by Django 4.1.5 on 2023-01-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_phone_checked_in_phone_checked_in_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone_Category',
            new_name='Product_Category',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
